<a href="https://colab.research.google.com/github/dinesh2018iitism/Learning-Python-From-PW/blob/main/Numpy_Assignments.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Theoretical Questions:**

1. Explain the purpose and advantages of NumPy in scientific computing and data analysis. How does it
enhance Python's capabilities for numerical operations?


In [ ]:
'''
NumPy is a powerful library in Python.
Numpy providies multi-dimensional arrays and matrices,
It has a collection of high-level mathematical functions to perform fast computations.

Advantage of using Numpy:

1. Efficient Memory Usage,
2. Fast Computation:
3. Support for Multi-Dimensional Arrays:
4. Broad Mathematical Functionality:
5. NumPy integrates with other scientific libraries in Python, such as SciPy.

NumPy Enhances Python's Numerical Capabilities:

In Numpy we can do Array Operations, broadcasting, linear algebra related problems, random number generation.

'''

2. Compare and contrast np.mean() and np.average() functions in NumPy. When would you use one over the
other?

In [10]:
"""
 np.mean():
  It computes the arithmetic mean (or average) of the elements along a specified axis.
  np.mean() does not support weights.
   calculates the mean by dividing the sum of all elements by the number of elements.
  Syntax: np.mean(arr, axis=None)
"""
import numpy as np
arr = np.array([1, 2, 3, 4, 5])
print(np.mean(arr))

'''
np.average()
It computes the weighted average of array elements along a specified axis.
We can provide weights to each element, and np.average() will compute the weighted mean accordingly
Syntax: np.average(arr, axis=None, weights=None)
'''
arr = np.array([1, 2, 3, 4, 5])
weights = np.array([1, 2, 3, 4, 5])
print(np.average(arr, weights=weights))



3.0
3.6666666666666665


3. Describe the methods for reversing a NumPy array along different axes. Provide examples for 1D and 2D
arrays.

In [11]:
##Reversing a 1D Array
import numpy as np

arr_1d = np.array([1, 2, 3, 4, 5])
reversed_arr_1d = arr_1d[::-1]
print(reversed_arr_1d)


[5 4 3 2 1]


In [12]:
##Reversing a 2D Array

import numpy as np
arr_2d = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])
reversed_rows = arr_2d[::-1, :]
print(reversed_rows)


[[7 8 9]
 [4 5 6]
 [1 2 3]]


4. How can you determine the data type of elements in a NumPy array? Discuss the importance of data types
in memory management and performance.

In [ ]:
import numpy as np
arr = np.array([1, 2, 3, 4])
data_type = arr.dtype
print(data_type)

"""
Data type helps in efficiently managing memory
Data types influence the performance of mathematical operations.

"""


5. Define ndarrays in NumPy and explain their key features. How do they differ from standard Python lists?

In [15]:
import numpy as np
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr)
print(type(arr))
"""
Key Features of ndarrays:
1. Homogeneous Elements
2. Multidimensional
3. Fixed Size
4. Efficient Memory Usage
5. Vectorized Operations
"""
'''
ndarray ia Homogeneous but Python List is Heterogeneous
ndarray Can be multidimensional but Python List ia Primarily one-dimensional,
'''


[[1 2 3]
 [4 5 6]]
<class 'numpy.ndarray'>


'\nndarray ia Homogeneous but Python List is Heterogeneous \nndarray Can be multidimensional but Python List ia Primarily one-dimensional, \n'

6. Analyze the performance benefits of NumPy arrays over Python lists for large-scale numerical operations

In [16]:
'''
NumPy Arrays use memory efficiently by storing data in a compact way.
But Python Lists use more memory because each element is a separate object with extra overhead.

NumPy Arrays have fast, built-in math functions for calculations.
But Python Lists always equire loops and are slower for mathematical operations.

NumPy Arrays support advanced indexing and slicing efficiently.
BUT in Python Lists Indexing and slicing are less advanced and slower.

'''

'\nNumPy Arrays use memory efficiently by storing data in a compact way.\nBut Python Lists use more memory because each element is a separate object with extra overhead.\n\nNumPy Arrays have fast, built-in math functions for calculations.\nBut Python Lists always equire loops and are slower for mathematical operations.\n\nNumPy Arrays support advanced indexing and slicing efficiently.\nBUT in Python Lists Indexing and slicing are less advanced and slower.\n\n'

7. Compare vstack() and hstack() functions in NumPy. Provide examples demonstrating their usage and
output.


In [17]:
''' vstack() is nothing but Vertical Stack
it tacks arrays on top of each other in vertically
'''
import numpy as np
arr1 = np.array([[1, 2, 3],
                 [4, 5, 6]])

arr2 = np.array([[7, 8, 9],
                 [10, 11, 12]])

# Stack arrays vertically
result_vstack = np.vstack((arr1, arr2))
print(result_vstack)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [18]:
'''
hstack() in nothing but Horizontal Stack
it Stacks arrays side by side horizontally.
'''

import numpy as np
arr1 = np.array([[1, 2, 3],
                 [4, 5, 6]])

arr2 = np.array([[7, 8],
                 [9, 10]])

# Stack arrays horizontally
result_hstack = np.hstack((arr1, arr2))
print(result_hstack)


[[ 1  2  3  7  8]
 [ 4  5  6  9 10]]


8. Explain the differences between fliplr() and flipud() methods in NumPy, including their effects on various
array dimensions.

In [19]:
# fliplr() - Flip Left-Right
#It reverses the order of columns in a 2D array.
import numpy as np

arr = np.array([[1, 2, 3],
                [4, 5, 6]])

# Flip left-right
result_fliplr = np.fliplr(arr)

print(result_fliplr)



[[3 2 1]
 [6 5 4]]


In [20]:
##flipud() - Flip Up-Down
#It reverses the order of rows in a 2D array.
import numpy as np
arr = np.array([[1, 2, 3],
                [4, 5, 6]])

# Flip up-down
result_flipud = np.flipud(arr)

print(result_flipud)


[[4 5 6]
 [1 2 3]]


9. Discuss the functionality of the array_split() method in NumPy. How does it handle uneven splits?

In [21]:
##The array_split() is used for split an array into multiple sub-arrays
##Spliting into equal parts
import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
split_arr = np.array_split(arr, 3)

print(split_arr)

###Splitting with Uneven Sizes:
import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
# Split at specific indices
split_arr = np.array_split(arr, [2, 5])

print(split_arr)




[array([1, 2, 3]), array([4, 5, 6]), array([7, 8, 9])]
[array([1, 2]), array([3, 4, 5]), array([6, 7, 8, 9])]


10. Explain the concepts of vectorization and broadcasting in NumPy. How do they contribute to efficient array
operations?

In [24]:
'''
Vectorization:
Perform operations on entire arrays rather than element-by-element.
Here Operations are generally much faster than using Python loops
Code using in operations is often more concise and easier to read.
'''
import numpy as np
a = np.array([1, 2, 3, 4, 5])
b = np.array([10, 20, 30, 40, 50])
result = a + b
print(result)


[11 22 33 44 55]


In [27]:
"""
Broadcasting:

Perform operations on arrays of different shapes in a way that they can be
made compatible for element-wise operations.
"""

import numpy as np
# Array with shape (3, 1)
a = np.array([[1], [2], [3]])
# Array with shape (1, 4)
b = np.array([[10, 20, 30, 40]])
# Broadcasting operation
result = a + b
print(result)


[[11 21 31 41]
 [12 22 32 42]
 [13 23 33 43]]


# **Practical Questions:**

1. Create a 3x3 NumPy array with random integers between 1 and 100. Then, interchange its rows and columns.

In [9]:
import numpy as np
array_3x3 = np.random.randint(1, 101, (3, 3))
transposed_array = array_3x3.T

# Display the original and transposed arrays
print("Original 3x3 Array:\n", array_3x3)
print("\nTransposed Array:\n", transposed_array)


Original 3x3 Array:
 [[ 9 94 13]
 [55 82 19]
 [74 72 91]]

Transposed Array:
 [[ 9 55 74]
 [94 82 72]
 [13 19 91]]


2. Generate a 1D NumPy array with 10 elements. Reshape it into a 2x5 array, then into a 5x2 array.

In [8]:
import numpy as np
array_1d = np.arange(10)
array_2x5 = array_1d.reshape(2, 5)
array_5x2 = array_2x5.reshape(5, 2)
# Display the original 1D array, 2x5 array, and 5x2 array
print("Original 1D Array:\n", array_1d)
print("\n2x5 Array:\n", array_2x5)
print("\n5x2 Array:\n", array_5x2)


Original 1D Array:
 [0 1 2 3 4 5 6 7 8 9]

2x5 Array:
 [[0 1 2 3 4]
 [5 6 7 8 9]]

5x2 Array:
 [[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


3. Create a 4x4 NumPy array with random float values. Add a border of zeros around it, resulting in a 6x6 array.

In [6]:
import numpy as np
array_4x4 = np.random.rand(4, 4)
array_6x6 = np.pad(array_4x4, pad_width=1, mode='constant', constant_values=0)
# Display the original 4x4 array and the new 6x6 array
print("Original 4x4 Array:\n", array_4x4)

print("\n6x6 Array with Border of Zeros:\n", array_6x6)


Original 4x4 Array:
 [[0.73933075 0.88295616 0.75161951 0.0755877 ]
 [0.49584152 0.03875546 0.02049304 0.76277661]
 [0.07079817 0.02936808 0.43409406 0.90988287]
 [0.28204055 0.11236379 0.41862438 0.03982771]]

6x6 Array with Border of Zeros:
 [[0.         0.         0.         0.         0.         0.        ]
 [0.         0.73933075 0.88295616 0.75161951 0.0755877  0.        ]
 [0.         0.49584152 0.03875546 0.02049304 0.76277661 0.        ]
 [0.         0.07079817 0.02936808 0.43409406 0.90988287 0.        ]
 [0.         0.28204055 0.11236379 0.41862438 0.03982771 0.        ]
 [0.         0.         0.         0.         0.         0.        ]]


4. Using NumPy, create an array of integers from 10 to 60 with a step of 5.



In [5]:
import numpy as np
array = np.arange(10, 65, 5)
print(array)


[10 15 20 25 30 35 40 45 50 55 60]


5. Create a NumPy array of strings ['python', 'numpy', 'pandas']. Apply different case transformations
(uppercase, lowercase, title case, etc.) to each element.

In [4]:
import numpy as np
words_array = np.array(['python', 'numpy', 'pandas'])
uppercase_words = np.char.upper(words_array)
lowercase_words = np.char.lower(words_array)
titlecase_words = np.char.title(words_array)
print("Original Words:", words_array)
print("Uppercase:", uppercase_words)
print("Lowercase:", lowercase_words)
print("Title Case:", titlecase_words)


Original Words: ['python' 'numpy' 'pandas']
Uppercase: ['PYTHON' 'NUMPY' 'PANDAS']
Lowercase: ['python' 'numpy' 'pandas']
Title Case: ['Python' 'Numpy' 'Pandas']


6. Generate a NumPy array of words. Insert a space between each character of every word in the array.

In [3]:
import numpy as np
words_array = np.array(['dinesh', 'halder', 'physics', 'mathematics'])
spaced_words = np.array([' '.join(word) for word in words_array])
# Display the results
print("Original Words:", words_array)
print("Words with spaces:", spaced_words)


Original Words: ['dinesh' 'halder' 'physics' 'mathematics']
Words with spaces: ['d i n e s h' 'h a l d e r' 'p h y s i c s' 'm a t h e m a t i c s']


7. Create two 2D NumPy arrays and perform element-wise addition, subtraction, multiplication, and division.

In [2]:
import numpy as np
array1 = np.array([[1, 2, 3],
                   [4, 5, 6]])

array2 = np.array([[7, 8, 9],
                   [10, 11, 12]])
addition_result = np.add(array1, array2)
subtraction_result = np.subtract(array2, array1)
multiplication_result = np.multiply(array1, array2)
division_result = np.divide(array2, array1)
print("Addition:\n", addition_result)
print("Subtraction:\n", subtraction_result)
print("Multiplication:\n", multiplication_result)
print("Division:\n", division_result)


Addition:
 [[ 8 10 12]
 [14 16 18]]
Subtraction:
 [[6 6 6]
 [6 6 6]]
Multiplication:
 [[ 7 16 27]
 [40 55 72]]
Division:
 [[7.  4.  3. ]
 [2.5 2.2 2. ]]


8. Use NumPy to create a 5x5 identity matrix, then extract its diagonal elements.

In [ ]:
import numpy as np

# Creating an 5x5 identity matrix
identity_matrix = np.eye(5)

# Step 2: Extract the diagonal elements
diagonal_elements = np.diag(identity_matrix)

# Display the identity matrix and its diagonal elements
print("5x5 Identity Matrix:\n", identity_matrix)
print("Diagonal Elements:", diagonal_elements)


5x5 Identity Matrix:
 [[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
Diagonal Elements: [1. 1. 1. 1. 1.]


9. Generate a NumPy array of 100 random integers between 0 and 1000. Find and display all prime numbers in
this array.

In [ ]:
import numpy as np

#Here First I am Generate a NumPy array of 100 random integers between 0 and 1000
random_integers = np.random.randint(0, 1000, 100)

#check if a number is prime
def is_prime(n):
    if n < 2:
        return False
    for i in range(2, int(np.sqrt(n)) + 1):
      ##If the number is not divisible by any number from 2 up to its square root, it's a prime number.
        if n % i == 0:
            return False
    return True
prime_numbers = [num for num in random_integers if is_prime(num)]
#Display the prime number
print("Prime numbers in the array:", prime_numbers)


Prime numbers in the array: [157, 239, 859, 373, 43, 151, 17, 521, 827, 269, 317, 211, 883, 73, 41, 593, 149, 769]


10. Create a NumPy array representing daily temperatures for a month. Calculate and display the weekly
averages.

In [ ]:
import numpy as np

# I am creating daily temp for 30 days
daily_temperatures = np.array([30, 32, 33, 29, 31, 30, 28,
                               35, 36, 34, 33, 32, 31, 30,
                               29, 30, 31, 32, 33, 34, 35,
                               36, 37, 38, 39, 38, 37, 36,
                               35, 34])

# I am going to Reshape the array into weeks (4 weeks, 7 days each, last week 2 days)
weeks = daily_temperatures[:28].reshape(4, 7)

# Here we will Calculate weekly averages
weekly_averages = np.mean(weeks, axis=1)

# Display the weekly averages
for i, avg in enumerate(weekly_averages, 1):
    print(f"Week {i} average temperature: {avg:.2f}°C")


Week 1 average temperature: 30.43°C
Week 2 average temperature: 33.00°C
Week 3 average temperature: 32.00°C
Week 4 average temperature: 37.29°C
